apiVersion: apps/v1
kind: Deployment
metadata:
  name: <% .Name %>
spec:
  template:
    spec:
      containers:
        - name: <% .Name %>
          resources:
            requests:
              memory: 64Mi
              cpu: 0.2
            limits:
              memory: 128Mi
              cpu: 0.6
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <% .Name %>
spec:
  maxReplicas: 3
  minReplicas: 1
