apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml
resources:
- ../../base
- external-secret.yml
- ingress.yml

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - ENVIRONMENT=staging
    - DOMAIN=<% index .Params `stagingHostRoot` %>
    - BACKEND_URL=https://<% index .Params `stagingBackendSubdomain` %><% index .Params `stagingHostRoot` %>
    - FRONTEND_URL=https://<% index .Params `stagingFrontendSubdomain` %><% index .Params `stagingHostRoot` %>
    - S3_BUCKET=files.<% index .Params `stagingHostRoot` %>
