apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml

resources:
- ../../base

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals: []
