apiVersion: apps/v1
kind: Deployment
metadata:
  name: <% .Name %>
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: <% .Name %>
  template:
    spec:
      serviceAccountName: backend-service
      automountServiceAccountToken: true
      containers:
        - name: <% .Name %>
          image: fake-image
          resources:
            requests:
              memory: 64Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.5
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - configMapRef:
              name: <% .Name %>-config
          - secretRef:
              name: <% .Name %>
          env:
          - name: SERVER_PORT
            value: "80"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <% .Name %>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <% .Name %>
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
